name: PR auto approve

on: [pull_request_target]

jobs:
  auto-approve:
    name: 'Pull request auto approve'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.1.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'semantic-release-bot'
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
